org: shnere
app: validadorcfdiapi
service: validadorcfdiapi
frameworkVersion: '2 || 3'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  profile: 'administracioncfdi'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    package:
      individually: true

plugins:
  - serverless-offline
